---
project_name: cloudflare-operator
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers:
  - image_templates:
      - ghcr.io/containeroo/cloudflare-operator:latest
      - ghcr.io/containeroo/cloudflare-operator:{{ .Version }}
    dockerfile: Dockerfile
    extra_files:
      - go.mod
      - go.sum
      - main.go
      - api
      - controllers
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/containeroo/cloudflare-operator
      - --label=org.opencontainers.image.source=https://github.com/containeroo/cloudflare-operator
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      #  - --label=org.opencontainers.image.licenses=MIT -> TBD
release:
  extra_files:
    - glob: ./crds.yaml
