# permissions for end users to view accounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: account-viewer-role
rules:
- apiGroups:
  - cloudflare-operator.io
  resources:
  - accounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudflare-operator.io
  resources:
  - accounts/status
  verbs:
  - get
