# permissions for end users to edit ips.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ip-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cloudflare-operator
    app.kubernetes.io/part-of: cloudflare-operator
    app.kubernetes.io/managed-by: kustomize
  name: ip-editor-role
rules:
- apiGroups:
  - cloudflare-operator.io
  resources:
  - ips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflare-operator.io
  resources:
  - ips/status
  verbs:
  - get
