# permissions for end users to view ips.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ip-viewer-role
rules:
- apiGroups:
  - cf.containeroo.ch
  resources:
  - ips
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cf.containeroo.ch
  resources:
  - ips/status
  verbs:
  - get
