# permissions for end users to edit zones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zone-editor-role
rules:
- apiGroups:
  - cf.containeroo.ch
  resources:
  - zones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cf.containeroo.ch
  resources:
  - zones/status
  verbs:
  - get
