# permissions for end users to view zones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zone-viewer-role
rules:
- apiGroups:
  - cloudflare-operator.io
  resources:
  - zones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudflare-operator.io
  resources:
  - zones/status
  verbs:
  - get
