---
apiVersion: cloudflare-operator.io/v1
kind: Zone
metadata:
  name: zone-sample
spec:
  name: containeroo-test.org
  prune: false
  ignoredRecords:
    A:
      - ^ignore-me.*$
    TXT:
      - _acme-challenge.containeroo-test.org
