site_name: Cloudflare Operator
site_url: https://docs.cf.containeroo.ch
site_description: cloudflare-operator documentation
site_author: containeroo

repo_url: https://github.com/containeroo/cloudflare-operator
edit_uri: 'edit/master/docs/content'
docs_dir: 'content'

theme:
  name: material
  custom_dir: 'theme'
  include_sidebar: true
  features:
    - navigation.instant
  favicon: assets/img/containeroo.png
  logo: assets/img/containeroo.png
  palette:
    - scheme: default
      primary: cyan
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist

plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
          remove_comments: true

nav:
  - 'Home': index.md
  - 'Core Concept': core_concept.md
  - 'Getting Started': getting_started.md
  - 'Installation': installation.md
  - 'Upgrade Notes': upgrade_notes.md
  - 'Operations': operations.md
  - 'API Reference': api_reference.md
  - 'Roadmap': roadmap.md
