{
 "title": "cloudflare-operator",
 "description": "overview for cloudflare-operator (https://github.com/containeroo/cloudflare-operator)",
 "tags": [ "cloudflare-operator" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Account",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cloudflare_operator_account_status"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\"cloudflare_operator_(account|dns_record|ip|zone)_status\"} == bool 1) or vector(0)"
    }
   ]
  },
  {
   "title": "Total managed DNSRecords",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(cloudflare_operator_dns_record_status)"
    }
   ]
  },
  {
   "title": "Failing DNSRecords",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(cloudflare_operator_dns_record_status > 0)\n"
    }
   ]
  },
  {
   "title": "Zones",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "cloudflare_operator_zone_status"
    }
   ]
  },
  {
   "title": "IPs",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 7, "y": 5 },
   "targets": [
    { "expr": "cloudflare_operator_ip_status" }
   ]
  },
  {
   "title": "DNSRecords",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "cloudflare_operator_dns_record_status"
    }
   ]
  }
 ]
}